export const FETCH_INTENT_PENDING = "FETCH_INTENT_PENDING";
export const FETCH_INTENT_SUCCESS = "FETCH_INTENT_SUCCESS";
export const FETCH_INTENT_FAIL = "FETCH_INTENT_FAIL";

export const ADD_BOT_MESSAGE_PENDING = "ADD_BOT_MESSAGE_PENDING";
export const ADD_BOT_MESSAGE_SUCCESS = "ADD_BOT_MESSAGE_SUCCESS";
export const ADD_BOT_MESSAGE_FAIL = "ADD_BOT_MESSAGE_FAIL";
